// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSDmflGbpk5-Zd-9mrGjRuhwgdya3iH8w',
    appId: '1:852725765142:web:5fd980b927e2e61e635137',
    messagingSenderId: '852725765142',
    projectId: 'fir-app-a2468',
    authDomain: 'fir-app-a2468.firebaseapp.com',
    storageBucket: 'fir-app-a2468.appspot.com',
    measurementId: 'G-PWTK5WYP50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ65CtC9hzMMonlU2WIoY9E2UD0BydajA',
    appId: '1:852725765142:android:4b6d4ee5ac844aee635137',
    messagingSenderId: '852725765142',
    projectId: 'fir-app-a2468',
    storageBucket: 'fir-app-a2468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_L1bxh303nZNfKmCFEZn6BmLhA-LNjVA',
    appId: '1:852725765142:ios:cb845508c05aff3b635137',
    messagingSenderId: '852725765142',
    projectId: 'fir-app-a2468',
    storageBucket: 'fir-app-a2468.appspot.com',
    iosClientId: '852725765142-kul7td0tnte6utnut85n74bc34uduno4.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );
}
